### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [xoofx/xoofx.github.io#3]
I recently stumbled upon a blog post on your site, but it seems to lack IPv6 support.

Since it's hosted on GitHub Pages, it can be fixed as follows:
1. Modify your GitHub Pages custom domain to point to `www.xoofx.com` instead of `xoofx.com`
2. Add a CNAME record for `xoofx.github.io` to `www.xoofx.com`
3. Add an AAAA record for `2a04:4e42:9::403` to xoofx.com (or if possible use an ANAME for `xoofx.github.io`)

**Comment by xoofx** [comment]
Redirecting xoofx.com back to xoofx.github.com
